### ISSUE TITLE
ability to package varnish on its own

### ISSUE THREAD

**Issue by gquintard** [xcir/vmod-packager#7]
currently, packaging varnish requires to package a vmod first, which is a bit annoying if one only cares about varnish

**Comment by xcir** [comment]
Yes, I'd like to do something about this too.
I originally created it with the idea of building VMOD packages, and later added the idea that it would be useful to build Varnish packages as well, so this is how it turned out.
I'm considering to build only Varnish with some options or by not specifying vmod source and specifying -k.

**Comment by xcir** [comment]
```
xcir@build01:~/git/vmod-packager$  ./vmod-packager.sh -k -d arch -v trunk -t
...
##################################################
        docker image: vmod-packager/arch:trunk-5598410656eaa2149d31af8fd421faea5a6f45f8
                Dist: arch
     Varnish Version: trunk
        Varnish hash: 5598410656eaa2149d31af8fd421faea5a6f45f8
         Varnish VRT: 140
           VMOD name: 
        VMOD Version: 140.0.1
    Enable skip test
              Status: SUCCESS
xcir@build01:~/git/vmod-packager$ ls pkgs/arch/varnish/
varnish-20220119.5598410-1-x86_64.pkg.tar.zst
```
I may fix the display :)
